apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deploy-deployment
  namespace: cicd
  labels:
    app: auto-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-deploy
  template:
    metadata:
      labels:
        app: auto-deploy
    spec:
      serviceAccountName: auto-deploy
      containers:
      - name: auto-deploy
        image: sprawlers/git-k8s-auto-deploy:23c101606766cefab1b34ccdd63a9f64188d59c6
        ports:
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-deploy-service
  namespace: cicd
spec:
  selector:
    app: auto-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auto-deploy-ingress
  namespace: cicd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - test.sprawl.team
    secretName: auto-deploy-tls
  rules:
  - host: test.sprawl.team
    http:
      paths:
      - backend:
          serviceName: auto-deploy-service
          servicePort: 80
